use std::path::PathBuf;
use tempfile::TempDir;

use selexqc::analyze::{AnalyzeConfig, run_analyze};
use selexqc::cluster::{ClusterConfig, run_cluster};
use selexqc::compare::{CompareConfig, run_compare};
use selexqc::construct::Segment;
use selexqc::count::{CountConfig, OutputFormat, run_count};
use selexqc::enrich::{EnrichConfig, run_enrich};
use selexqc::search::{SearchConfig, run_search};
use selexqc::validate::{ValidateConfig, run_validate};

fn test_segments() -> Vec<Segment> {
    vec![
        Segment::Const {
            sequence: b"AAAAAA".to_vec(),
        },
        Segment::Rand {
            min_len: 8,
            max_len: 12,
        },
        Segment::Const {
            sequence: b"TTTTTT".to_vec(),
        },
    ]
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("test.fastq")
}

#[test]
fn analyze_produces_outputs() {
    let tmp = TempDir::new().unwrap();
    let output_prefix = tmp.path().join("result").to_str().unwrap().to_string();

    run_analyze(&AnalyzeConfig {
        input: fixture_path(),
        output_prefix: output_prefix.clone(),
        segments: test_segments(),
        strict_boundaries: true,
        near_miss_depth: 3,
        filter: true,
        extract_random: true,
        quiet: true,
    })
    .unwrap();

    // Verify output files exist
    assert!(
        std::path::Path::new(&format!("{}.parquet", output_prefix)).exists(),
        "Parquet file should exist"
    );
    assert!(
        std::path::Path::new(&format!("{}.fasta", output_prefix)).exists(),
        "Ranked FASTA should exist"
    );
    assert!(
        std::path::Path::new(&format!("{}.report.json", output_prefix)).exists(),
        "JSON report should exist"
    );
    assert!(
        std::path::Path::new(&format!("{}.report.txt", output_prefix)).exists(),
        "Text report should exist"
    );
    assert!(
        std::path::Path::new(&format!("{}.filtered.fq", output_prefix)).exists(),
        "Filtered FASTQ should exist"
    );
    assert!(
        std::path::Path::new(&format!("{}.random.fa", output_prefix)).exists(),
        "Random region FASTA should exist"
    );
}

#[test]
fn analyze_json_report_contents() {
    let tmp = TempDir::new().unwrap();
    let output_prefix = tmp.path().join("result").to_str().unwrap().to_string();

    run_analyze(&AnalyzeConfig {
        input: fixture_path(),
        output_prefix: output_prefix.clone(),
        segments: test_segments(),
        strict_boundaries: true,
        near_miss_depth: 3,
        filter: false,
        extract_random: false,
        quiet: true,
    })
    .unwrap();

    let json_path = format!("{}.report.json", output_prefix);
    let content = std::fs::read_to_string(&json_path).unwrap();
    let report: serde_json::Value = serde_json::from_str(&content).unwrap();

    // 11 total reads (generated by examples/generate_fixture.rs)
    assert_eq!(report["summary"]["total_reads"], 11);

    // Valid: seq1, seq2, seq3, seq4(min_rand), seq11(dup) = 5
    // Invalid: seq5(rand short), seq6(rand long), seq7(missing 3p),
    //          seq8(missing 5p), seq9(leading gap), seq10(trailing gap) = 6
    assert_eq!(report["summary"]["valid"], 5);
    assert_eq!(report["summary"]["invalid"], 6);
}

#[test]
fn analyze_ranked_fasta_format() {
    let tmp = TempDir::new().unwrap();
    let output_prefix = tmp.path().join("result").to_str().unwrap().to_string();

    run_analyze(&AnalyzeConfig {
        input: fixture_path(),
        output_prefix: output_prefix.clone(),
        segments: test_segments(),
        strict_boundaries: true,
        near_miss_depth: 0,
        filter: false,
        extract_random: false,
        quiet: true,
    })
    .unwrap();

    let fasta = std::fs::read_to_string(format!("{}.fasta", output_prefix)).unwrap();
    let first_line = fasta.lines().next().unwrap();

    // FASTAptamer format: >RANK-READS-RPM
    assert!(
        first_line.starts_with(">1-"),
        "First entry should be rank 1, got: {}",
        first_line
    );
    // Most frequent sequence (seq1 = seq2 = seq11, count=3)
    assert!(
        first_line.contains("-3-"),
        "Most frequent should have count 3, got: {}",
        first_line
    );
}

#[test]
fn count_produces_parquet() {
    let tmp = TempDir::new().unwrap();
    let output_prefix = tmp.path().join("counts").to_str().unwrap().to_string();

    run_count(&CountConfig {
        input: fixture_path(),
        output_prefix: output_prefix.clone(),
        format: OutputFormat::Parquet,
        rpm: true,
        quiet: true,
    })
    .unwrap();

    assert!(std::path::Path::new(&format!("{}.parquet", output_prefix)).exists());
}

#[test]
fn count_produces_csv() {
    let tmp = TempDir::new().unwrap();
    let output_prefix = tmp.path().join("counts").to_str().unwrap().to_string();

    run_count(&CountConfig {
        input: fixture_path(),
        output_prefix: output_prefix.clone(),
        format: OutputFormat::Csv,
        rpm: true,
        quiet: true,
    })
    .unwrap();

    let csv_path = format!("{}.csv", output_prefix);
    let content = std::fs::read_to_string(&csv_path).unwrap();
    let lines: Vec<&str> = content.lines().collect();

    assert_eq!(lines[0], "rank,sequence,count,rpm");
    // 11 reads, 3 are duplicates (seq1=seq2=seq11) → 9 unique sequences
    assert_eq!(
        lines.len(),
        10,
        "Expected header + 9 unique sequences, got {}",
        lines.len()
    );
}

#[test]
fn count_produces_fasta() {
    let tmp = TempDir::new().unwrap();
    let output_prefix = tmp.path().join("counts").to_str().unwrap().to_string();

    run_count(&CountConfig {
        input: fixture_path(),
        output_prefix: output_prefix.clone(),
        format: OutputFormat::Fasta,
        rpm: false,
        quiet: true,
    })
    .unwrap();

    let fasta_path = format!("{}.fasta", output_prefix);
    let content = std::fs::read_to_string(&fasta_path).unwrap();
    // First header should be the most frequent sequence (seq1=seq2=seq11, count=3)
    assert!(
        content.starts_with(">1-3-"),
        "Should start with rank 1, count 3"
    );
}

#[test]
fn validate_produces_reports() {
    let tmp = TempDir::new().unwrap();
    let output_prefix = tmp.path().join("val").to_str().unwrap().to_string();

    run_validate(&ValidateConfig {
        input: fixture_path(),
        output_prefix: output_prefix.clone(),
        segments: test_segments(),
        strict_boundaries: true,
        near_miss_depth: 3,
        filter: true,
        extract_random: false,
        quiet: true,
    })
    .unwrap();

    assert!(std::path::Path::new(&format!("{}.report.json", output_prefix)).exists());
    assert!(std::path::Path::new(&format!("{}.report.txt", output_prefix)).exists());
    assert!(std::path::Path::new(&format!("{}.filtered.fq", output_prefix)).exists());
}

#[test]
fn validate_filtered_output_only_valid() {
    let tmp = TempDir::new().unwrap();
    let output_prefix = tmp.path().join("val").to_str().unwrap().to_string();

    run_validate(&ValidateConfig {
        input: fixture_path(),
        output_prefix: output_prefix.clone(),
        segments: test_segments(),
        strict_boundaries: true,
        near_miss_depth: 0,
        filter: true,
        extract_random: false,
        quiet: true,
    })
    .unwrap();

    let filtered = std::fs::read_to_string(format!("{}.filtered.fq", output_prefix)).unwrap();
    // Each FASTQ record is 4 lines. 5 valid sequences = 20 lines
    let lines: Vec<&str> = filtered.lines().collect();
    assert_eq!(
        lines.len(),
        20,
        "Expected 5 valid sequences (20 lines), got {}",
        lines.len()
    );
}

#[test]
fn analyze_combination_analysis() {
    let tmp = TempDir::new().unwrap();
    let output_prefix = tmp.path().join("result").to_str().unwrap().to_string();

    run_analyze(&AnalyzeConfig {
        input: fixture_path(),
        output_prefix: output_prefix.clone(),
        segments: test_segments(),
        strict_boundaries: true,
        near_miss_depth: 0,
        filter: false,
        extract_random: false,
        quiet: true,
    })
    .unwrap();

    let content = std::fs::read_to_string(format!("{}.report.json", output_prefix)).unwrap();
    let report: serde_json::Value = serde_json::from_str(&content).unwrap();

    // combinations should be an array
    let combos = report["combinations"].as_array().unwrap();
    assert!(!combos.is_empty(), "Should have combination data");

    // First combo should be the most frequent
    let first = &combos[0];
    assert!(first["count"].as_u64().unwrap() > 0);
}

// --- Phase 2: enrich, compare, search ---

/// Helper: run analyze to produce a Parquet file for downstream tests.
fn produce_parquet(tmp: &TempDir, name: &str) -> String {
    let prefix = tmp.path().join(name).to_str().unwrap().to_string();
    run_analyze(&AnalyzeConfig {
        input: fixture_path(),
        output_prefix: prefix.clone(),
        segments: test_segments(),
        strict_boundaries: true,
        near_miss_depth: 0,
        filter: false,
        extract_random: false,
        quiet: true,
    })
    .unwrap();
    format!("{}.parquet", prefix)
}

#[test]
fn enrich_two_rounds() {
    let tmp = TempDir::new().unwrap();
    let pq1 = produce_parquet(&tmp, "r1");
    let pq2 = produce_parquet(&tmp, "r2");
    let out = tmp.path().join("enrich").to_str().unwrap().to_string();

    run_enrich(&EnrichConfig {
        inputs: vec![PathBuf::from(&pq1), PathBuf::from(&pq2)],
        output_prefix: out.clone(),
        labels: vec!["r1".into(), "r2".into()],
        quiet: true,
    })
    .unwrap();

    let tsv_path = format!("{}.enrichment.tsv", out);
    assert!(
        std::path::Path::new(&tsv_path).exists(),
        "Enrichment TSV should exist"
    );

    let content = std::fs::read_to_string(&tsv_path).unwrap();
    let lines: Vec<&str> = content.lines().collect();
    // Header + 9 unique sequences
    assert!(lines.len() > 1, "Should have header + data rows");
    // Header should contain round labels
    assert!(lines[0].contains("r1_rpm"));
    assert!(lines[0].contains("r2_rpm"));
    assert!(lines[0].contains("fold_r2_vs_r1"));
}

#[test]
fn enrich_three_rounds_has_overall_fold() {
    let tmp = TempDir::new().unwrap();
    let pq1 = produce_parquet(&tmp, "r1");
    let pq2 = produce_parquet(&tmp, "r3");
    let pq3 = produce_parquet(&tmp, "r5");
    let out = tmp.path().join("enrich3").to_str().unwrap().to_string();

    run_enrich(&EnrichConfig {
        inputs: vec![
            PathBuf::from(&pq1),
            PathBuf::from(&pq2),
            PathBuf::from(&pq3),
        ],
        output_prefix: out.clone(),
        labels: vec!["r1".into(), "r3".into(), "r5".into()],
        quiet: true,
    })
    .unwrap();

    let content =
        std::fs::read_to_string(format!("{}.enrichment.tsv", out)).unwrap();
    let header = content.lines().next().unwrap();
    // 3 rounds → adjacent folds + overall fold
    assert!(header.contains("fold_r3_vs_r1"));
    assert!(header.contains("fold_r5_vs_r3"));
    assert!(header.contains("fold_r5_vs_r1"));
}

#[test]
fn compare_produces_tsv_and_histogram() {
    let tmp = TempDir::new().unwrap();
    let pq1 = produce_parquet(&tmp, "x");
    let pq2 = produce_parquet(&tmp, "y");
    let out = tmp.path().join("cmp").to_str().unwrap().to_string();

    run_compare(&CompareConfig {
        input_x: PathBuf::from(&pq1),
        input_y: PathBuf::from(&pq2),
        output_prefix: out.clone(),
        label_x: "round3".into(),
        label_y: "round5".into(),
        quiet: true,
    })
    .unwrap();

    let tsv = format!("{}.compare.tsv", out);
    let hist = format!("{}.compare.histogram.tsv", out);
    assert!(std::path::Path::new(&tsv).exists(), "Compare TSV should exist");
    assert!(
        std::path::Path::new(&hist).exists(),
        "Histogram TSV should exist"
    );

    // Histogram should have 102 bins + header
    let hist_content = std::fs::read_to_string(&hist).unwrap();
    let hist_lines: Vec<&str> = hist_content.lines().collect();
    assert_eq!(hist_lines.len(), 103, "102 bins + header");

    // Compare TSV header should have labels
    let tsv_content = std::fs::read_to_string(&tsv).unwrap();
    let header = tsv_content.lines().next().unwrap();
    assert!(header.contains("round3_rpm"));
    assert!(header.contains("round5_rpm"));
    assert!(header.contains("log2_ratio"));
}

#[test]
fn compare_same_file_log2_zero() {
    let tmp = TempDir::new().unwrap();
    let pq = produce_parquet(&tmp, "same");
    let out = tmp.path().join("self_cmp").to_str().unwrap().to_string();

    run_compare(&CompareConfig {
        input_x: PathBuf::from(&pq),
        input_y: PathBuf::from(&pq),
        output_prefix: out.clone(),
        label_x: "a".into(),
        label_y: "b".into(),
        quiet: true,
    })
    .unwrap();

    let content = std::fs::read_to_string(format!("{}.compare.tsv", out)).unwrap();
    // All log2 ratios should be 0 (same file)
    for line in content.lines().skip(1) {
        let fields: Vec<&str> = line.split('\t').collect();
        let log2: f64 = fields.last().unwrap().parse().unwrap();
        assert!(
            log2.abs() < 0.001,
            "Self-compare should have log2=0, got {}",
            log2
        );
    }
}

#[test]
fn search_iupac_and_mode() {
    let tmp = TempDir::new().unwrap();
    let pq = produce_parquet(&tmp, "counts");
    let out = tmp.path().join("search").to_str().unwrap().to_string();

    // Search for "NNNNNN" (matches everything) — should find all 9 sequences
    run_search(&SearchConfig {
        input: PathBuf::from(&pq),
        output_prefix: out.clone(),
        patterns: vec!["NNNNNN".into()],
        match_all: true,
        quiet: true,
    })
    .unwrap();

    let fasta = std::fs::read_to_string(format!("{}.search.fasta", out)).unwrap();
    let seq_count = fasta.lines().filter(|l| l.starts_with('>')).count();
    assert_eq!(seq_count, 9, "NNNNNN should match all 9 unique sequences");
}

#[test]
fn search_specific_pattern() {
    let tmp = TempDir::new().unwrap();
    let pq = produce_parquet(&tmp, "counts");
    let out = tmp.path().join("search2").to_str().unwrap().to_string();

    // Search for "AAAAAA" — only sequences containing AAAAAA
    run_search(&SearchConfig {
        input: PathBuf::from(&pq),
        output_prefix: out.clone(),
        patterns: vec!["AAAAAA".into()],
        match_all: true,
        quiet: true,
    })
    .unwrap();

    let fasta = std::fs::read_to_string(format!("{}.search.fasta", out)).unwrap();
    let seq_count = fasta.lines().filter(|l| l.starts_with('>')).count();
    // Sequences with AAAAAA: all that have the 5' primer
    assert!(seq_count > 0, "Should find sequences with AAAAAA");
    assert!(seq_count < 9, "Should not match all sequences");
}

#[test]
fn search_or_mode() {
    let tmp = TempDir::new().unwrap();
    let pq = produce_parquet(&tmp, "counts");
    let out = tmp.path().join("search_or").to_str().unwrap().to_string();

    // Search for "TTTTTT" OR "GCATGC" — TTTTTT in most, GCATGC in seq3
    run_search(&SearchConfig {
        input: PathBuf::from(&pq),
        output_prefix: out.clone(),
        patterns: vec!["TTTTTT".into(), "GCATGC".into()],
        match_all: false, // OR mode
        quiet: true,
    })
    .unwrap();

    let fasta = std::fs::read_to_string(format!("{}.search.fasta", out)).unwrap();
    let seq_count = fasta.lines().filter(|l| l.starts_with('>')).count();
    assert!(seq_count > 0, "OR mode should match sequences with TTTTTT or GCATGC");
}

// --- Phase 3: cluster ---

#[test]
fn cluster_produces_outputs() {
    let tmp = TempDir::new().unwrap();
    let pq = produce_parquet(&tmp, "counts");
    let out = tmp.path().join("clustered").to_str().unwrap().to_string();

    run_cluster(&ClusterConfig {
        input: PathBuf::from(&pq),
        output_prefix: out.clone(),
        max_dist: 3,
        count_filter: None,
        max_clusters: None,
        quiet: true,
    })
    .unwrap();

    assert!(
        std::path::Path::new(&format!("{}.clustered.fasta", out)).exists(),
        "Clustered FASTA should exist"
    );
    assert!(
        std::path::Path::new(&format!("{}.clusters.tsv", out)).exists(),
        "Cluster summary should exist"
    );
}

#[test]
fn cluster_fasta_format() {
    let tmp = TempDir::new().unwrap();
    let pq = produce_parquet(&tmp, "counts");
    let out = tmp.path().join("cl").to_str().unwrap().to_string();

    run_cluster(&ClusterConfig {
        input: PathBuf::from(&pq),
        output_prefix: out.clone(),
        max_dist: 3,
        count_filter: None,
        max_clusters: None,
        quiet: true,
    })
    .unwrap();

    let fasta = std::fs::read_to_string(format!("{}.clustered.fasta", out)).unwrap();
    let first_header = fasta.lines().next().unwrap();
    // FASTAptamer format: >Rank-Reads-RPM-Cluster#-ClusterRank-EditDistance
    let parts: Vec<&str> = first_header[1..].split('-').collect();
    assert!(parts.len() >= 6, "Header should have 6+ fields: {}", first_header);
}

#[test]
fn cluster_summary_has_all_sequences() {
    let tmp = TempDir::new().unwrap();
    let pq = produce_parquet(&tmp, "counts");
    let out = tmp.path().join("cl2").to_str().unwrap().to_string();

    run_cluster(&ClusterConfig {
        input: PathBuf::from(&pq),
        output_prefix: out.clone(),
        max_dist: 100, // very permissive — everything in 1 cluster
        count_filter: None,
        max_clusters: None,
        quiet: true,
    })
    .unwrap();

    let summary = std::fs::read_to_string(format!("{}.clusters.tsv", out)).unwrap();
    let data_lines: Vec<&str> = summary.lines().skip(1).collect();
    // With dist=100, should be 1 cluster containing all 9 sequences
    assert_eq!(data_lines.len(), 1, "Expected 1 cluster with dist=100");
    let fields: Vec<&str> = data_lines[0].split('\t').collect();
    let size: usize = fields[1].parse().unwrap();
    assert_eq!(size, 9, "Single cluster should contain all 9 sequences");
}

#[test]
fn cluster_with_count_filter() {
    let tmp = TempDir::new().unwrap();
    let pq = produce_parquet(&tmp, "counts");
    let out = tmp.path().join("cl3").to_str().unwrap().to_string();

    run_cluster(&ClusterConfig {
        input: PathBuf::from(&pq),
        output_prefix: out.clone(),
        max_dist: 3,
        count_filter: Some(2), // only sequences with count >= 2
        max_clusters: None,
        quiet: true,
    })
    .unwrap();

    let summary = std::fs::read_to_string(format!("{}.clusters.tsv", out)).unwrap();
    let data_lines: Vec<&str> = summary.lines().skip(1).collect();
    // Only seq1=seq2=seq11 has count=3, rest have count=1
    assert_eq!(data_lines.len(), 1, "Only 1 sequence passes count>=2 filter");
}
